AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false

  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

